insert into public.funding_opportunities (
  org_id,
  funder,
  title,
  amount_min,
  amount_max,
  deadline,
  match_score,
  description,
  url,
  external_id,
  source_type,
  source_url,
  published_date,
  raw_text,
  title_original,
  title_de,
  lang_original,
  summary_de,
  topics,
  funders,
  eligibility,
  eligibility_reason,
  priority,
  classification_reason,
  amount_currency,
  own_contribution_required,
  nrw_required,
  applies_from_burundi_ok,
  ai_processed_at,
  ai_model
)
select
  orgs.id,
  seed.funder,
  seed.title_de,
  seed.amount_min,
  seed.amount_max,
  seed.deadline,
  seed.match_score,
  seed.summary_de,
  seed.source_url,
  seed.external_id,
  seed.source_type,
  seed.source_url,
  seed.published_date,
  seed.raw_text,
  seed.title_original,
  seed.title_de,
  seed.lang_original,
  seed.summary_de,
  seed.topics,
  seed.funders,
  seed.eligibility,
  seed.eligibility_reason,
  seed.priority,
  'Curated source profile from funding playbook.',
  seed.amount_currency,
  seed.own_contribution_required,
  seed.nrw_required,
  seed.applies_from_burundi_ok,
  now(),
  'curated'
from (
  values
    (
      'burundi-kids',
      'curated:europeaid-185435-dd-act-bi',
      'curated',
      'https://www.eeas.europa.eu/delegations/burundi',
      'EU Delegation to Burundi',
      'Renforcement des organisations de la societe civile au Burundi',
      'Renforcement des organisations de la societe civile au Burundi',
      'fr',
      date '2025-12-12',
      date '2026-03-24',
      1000000,
      1500000,
      'EUR',
      array['civil society', 'burundi', 'local partner', 'governance'],
      array['European Union', 'EU Delegation to Burundi'],
      'check',
      'Grundsaetzlich passend durch den lokalen Partner Fondation Stamm, aber zweistufiges EU-Verfahren, PADOR/Registrierung und sehr grosse Mindestfoerdersumme muessen geprueft werden.',
      72,
      'amber',
      'Die EU-Delegation in Burundi foerdert die Staerkung zivilgesellschaftlicher Organisationen. Der Aufruf ist fuer Burundi fachlich sehr relevant, verlangt aber ein formal starkes Antragsverfahren und lokale Partnerschaften. Fuer Burundi Kids ist dies eher eine Konsortiums- oder Partnerchance als ein einfacher Direktantrag.',
      'EU Delegation to Burundi call EuropeAid/185435/DD/ACT/BI: Renforcement des organisations de la societe civile au Burundi. Appel a propositions restreint, published 12 December 2025, deadline 24/03/2026 at 12.00 Brussels time. Documents in French. Grants reported around EUR 1,000,000 to EUR 1,500,000 and projects 36-48 months. Requires an INGO in partnership with at least one Burundian CSO.',
      null::boolean,
      false,
      true
    ),
    (
      'burundi-kids',
      'curated:bengo-private-traeger-burundi',
      'curated',
      'https://bengo.engagement-global.de/',
      'Engagement Global bengo',
      'BMZ-Foerderung fuer private Traeger in der Entwicklungszusammenarbeit',
      'Foerderung privater Traeger in der Entwicklungszusammenarbeit',
      'de',
      null::date,
      date '2026-09-30',
      50000,
      250000,
      'EUR',
      array['education', 'development cooperation', 'burundi', 'local partner'],
      array['BMZ', 'Engagement Global', 'bengo'],
      'yes',
      'Burundi Kids ist ein deutscher gemeinnuetziger Verein mit langjaehrigem lokalen Partner in Burundi; Eigenanteil und aktuelle Traegeranforderungen muessen im Antrag eingeplant werden.',
      90,
      'amber',
      'bengo unterstuetzt deutsche gemeinnuetzige Traeger bei entwicklungspolitischen Projekten mit Partnerorganisationen im Globalen Sueden. Fuer Burundi Kids passt dies gut zu Bildungs-, Schutz- und Gesundheitsprojekten in Burundi. Wichtig sind eine solide Wirkungslogik, Eigenanteil und die Abstimmung mit Fondation Stamm.',
      'Engagement Global bengo / BMZ private Traeger: German non-profit organizations can apply for development cooperation project funding with partner organizations in the Global South. Typical requirements include charitable status, local partner, own contribution and project experience.',
      true,
      false,
      false
    ),
    (
      'burundi-kids',
      'curated:sez-bwirkt-burundi',
      'curated',
      'https://sez.de/themen/projektfoerderung/',
      'SEZ Baden-Wuerttemberg',
      'bwirkt! Burundi Projektfoerderung',
      'bwirkt! Burundi Projektfoerderung',
      'de',
      null::date,
      date '2026-07-20',
      5000,
      20000,
      'EUR',
      array['burundi', 'education', 'partnership', 'small grants'],
      array['SEZ Baden-Wuerttemberg'],
      'check',
      'Inhaltlich sehr passend fuer Burundi-Projekte; zu pruefen ist, ob Burundi Kids selbst oder ein Partner die formalen Baden-Wuerttemberg-Anforderungen erfuellt.',
      78,
      'amber',
      'Die SEZ Baden-Wuerttemberg buendelt Projektfoerderung fuer entwicklungspolitische Partnerschaften, darunter Burundi-Bezuege. Fuer Burundi Kids ist dies als kleine bis mittlere Projektfoerderung interessant. Formale Landes- und Partnerschaftsanforderungen sollten vorab geprueft werden.',
      'SEZ Baden-Wuerttemberg project funding page covering development project funding and Burundi-related support lines including bwirkt! Burundi. Relevant for small project funding, partnerships and civil society initiatives.',
      null::boolean,
      false,
      true
    ),
    (
      'burundi-kids',
      'curated:brot-fuer-die-welt-partner-funding',
      'curated',
      'https://www.brot-fuer-die-welt.de/',
      'Brot fuer die Welt',
      'Partnerorientierte Projektfoerderung Bildung und Kinderrechte',
      'Partnerorientierte Projektfoerderung Bildung und Kinderrechte',
      'de',
      null::date,
      null::date,
      null::int,
      null::int,
      'EUR',
      array['education', 'children', 'partner funding', 'civil society'],
      array['Brot fuer die Welt'],
      'check',
      'Themen passen gut, aber Brot fuer die Welt arbeitet stark partner- und beziehungsbasiert; ein konkreter offener Call oder Zugangskanal muss geprueft werden.',
      66,
      'green',
      'Brot fuer die Welt ist thematisch relevant fuer Bildung, Kinderrechte und zivilgesellschaftliche Arbeit. Fuer Burundi Kids kann dies als Beobachtungsquelle und moeglicher Partnerkontakt sinnvoll sein. Ohne konkreten offenen Aufruf bleibt es eine Monitoring-Chance.',
      'Brot fuer die Welt works internationally on development cooperation, education, children rights, civil society and justice themes. Public calls for proposals are not consistently exposed as RSS/API; treat as curated monitoring source and relationship-based funding lead.',
      null::boolean,
      false,
      null::boolean
    ),
    (
      'burundi-kids',
      'curated:misereor-education-empowerment',
      'curated',
      'https://www.misereor.de/',
      'Misereor',
      'Projektfoerderung fuer Bildung, Gesundheit und Empowerment',
      'Projektfoerderung fuer Bildung, Gesundheit und Empowerment',
      'de',
      null::date,
      null::date,
      null::int,
      null::int,
      'EUR',
      array['education', 'health', 'empowerment', 'africa'],
      array['Misereor'],
      'check',
      'Themen und Region koennen passen, aber konkrete Foerderfenster, konfessionelle oder partnerbezogene Anforderungen und Antragstellerkreis muessen geprueft werden.',
      64,
      'green',
      'Misereor ist eine relevante Quelle fuer internationale Projektfoerderung in Bereichen wie Bildung, Gesundheit und Empowerment. Fuer Burundi Kids ist dies vor allem ein Monitoring- und Kontaktkanal. Eine konkrete Bewerbung haengt von aktuellen Programmen und Partneranforderungen ab.',
      'Misereor supports international development cooperation with themes including education, health, empowerment and civil society. No stable calls-for-proposals API or RSS for open NGO grant windows was identified; keep as curated source for monitoring.',
      null::boolean,
      false,
      null::boolean
    ),
    (
      'burundi-kids',
      'curated:deutscher-engagementpreis',
      'curated',
      'https://www.deutscher-engagementpreis.de/',
      'Deutscher Engagementpreis',
      'Deutscher Engagementpreis',
      'Deutscher Engagementpreis',
      'de',
      null::date,
      date '2026-06-30',
      null::int,
      null::int,
      'EUR',
      array['award', 'recognition', 'nomination'],
      array['Deutscher Engagementpreis'],
      'no',
      'Keine regulaere Projektfoerderung und keine freie Eigenbewerbung; relevant hoechstens als Oeffentlichkeits- oder Nominierungschance.',
      12,
      'green',
      'Der Deutsche Engagementpreis ist ein Anerkennungspreis und keine klassische Projektfoerderung. Fuer Burundi Kids ist er fuer Fundraising-Fristen weniger relevant. Eine Teilnahme setzt ueblicherweise eine Nominierung voraus.',
      'Deutscher Engagementpreis is an award/recognition programme. It is nomination-based and not a normal open project funding call. No self-application for standard project grants.',
      false,
      false,
      false
    ),
    (
      'wtg',
      'curated:eu-life-animal-welfare',
      'curated',
      'https://ec.europa.eu/info/funding-tenders/opportunities/data/referenceData/grantsTenders.json',
      'EU LIFE Programme',
      'Animal Welfare and Sustainable Agriculture',
      'Animal Welfare and Sustainable Agriculture',
      'en',
      null::date,
      date '2026-09-12',
      200000,
      600000,
      'EUR',
      array['animal welfare', 'agriculture', 'policy', 'consortium'],
      array['European Union', 'LIFE Programme'],
      'check',
      'Inhaltlich relevant fuer WTG, aber LIFE-Projekte sind gross, konsortial und formal aufwendig; Partnerstruktur und Eigenmittel pruefen.',
      78,
      'amber',
      'Ein EU-LIFE-Foerderfenster kann fuer Tierschutz in Landwirtschaft und Politikpiloten relevant sein. Fuer WTG waere dies eher ein Konsortiumsprojekt mit langer Vorbereitung. Budget- und Partneranforderungen muessen geprueft werden.',
      'EU LIFE Programme funding related to animal welfare and sustainable agriculture. Large grants, policy pilots and consortium projects. Relevant to WTG animal welfare work but requires formal EU application capacity.',
      true,
      false,
      false
    ),
    (
      'wtg',
      'curated:stray-animal-cofunding',
      'curated',
      'https://www.vier-pfoten.org/',
      'Vier Pfoten Foundation',
      'Stray Animal Welfare Co-funding',
      'Stray Animal Welfare Co-funding',
      'en',
      null::date,
      date '2026-07-18',
      30000,
      90000,
      'EUR',
      array['stray animals', 'spay neuter', 'shelter capacity'],
      array['Vier Pfoten Foundation'],
      'yes',
      'Direkter Themenfit fuer WTG-Programme zu Streunertieren; konkrete Ausschreibungsbedingungen und Kofinanzierung pruefen.',
      90,
      'amber',
      'Die Foerderung passt zu Streunertierarbeit, Kastrationsprogrammen und Shelter-Kapazitaet. WTG hat hierfuer einen starken fachlichen Fit. Die formalen Foerderbedingungen muessen vor Antragstellung geprueft werden.',
      'Co-funding for spay/neuter programs, shelter capacity and responsible ownership in developing countries. Relevant to WTG flagship stray dog work.',
      null::boolean,
      false,
      false
    )
) as seed(
  org_slug,
  external_id,
  source_type,
  source_url,
  funder,
  title_de,
  title_original,
  lang_original,
  published_date,
  deadline,
  amount_min,
  amount_max,
  amount_currency,
  topics,
  funders,
  eligibility,
  eligibility_reason,
  match_score,
  priority,
  summary_de,
  raw_text,
  own_contribution_required,
  nrw_required,
  applies_from_burundi_ok
)
join public.orgs on orgs.slug = seed.org_slug
on conflict (org_id, source_type, external_id) where external_id is not null
do update set
  funder = excluded.funder,
  title = excluded.title,
  amount_min = excluded.amount_min,
  amount_max = excluded.amount_max,
  deadline = excluded.deadline,
  match_score = excluded.match_score,
  description = excluded.description,
  url = excluded.url,
  source_url = excluded.source_url,
  published_date = excluded.published_date,
  raw_text = excluded.raw_text,
  title_original = excluded.title_original,
  title_de = excluded.title_de,
  lang_original = excluded.lang_original,
  summary_de = excluded.summary_de,
  topics = excluded.topics,
  funders = excluded.funders,
  eligibility = excluded.eligibility,
  eligibility_reason = excluded.eligibility_reason,
  priority = excluded.priority,
  classification_reason = excluded.classification_reason,
  amount_currency = excluded.amount_currency,
  own_contribution_required = excluded.own_contribution_required,
  nrw_required = excluded.nrw_required,
  applies_from_burundi_ok = excluded.applies_from_burundi_ok,
  ai_processed_at = excluded.ai_processed_at,
  ai_model = excluded.ai_model;
